### ISSUE TITLE
Don't show Dialog subtitle by default

### ISSUE THREAD

**Issue by reywright** [cbinsights/form-design-system#694]
https://cbinsights.github.io/form-design-system/fds-components/?path=/story/components-dialog--primary

<img width="553" alt="Screen Shot 2021-11-01 at 2 15 58 PM" src="https://user-images.githubusercontent.com/708820/139728268-20819366-73c5-47c1-a53d-8cafd811b1b1.png">

The subtitle here should not be shown by default, as it’s not a prop we want to be used commonly.

- Remove showing it by default in the first story
- [optional] add a different story just to show off the subtitle feature

**Comment by ivanhdez28** [comment]
can i have this issue assigned to me? thanks

**Comment by reywright** [comment]
solved! thanks @ivanhdez28 !
