### ISSUE TITLE
Update pull_request_template.md

### ISSUE THREAD

**Issue by reywright** [cbinsights/form-design-system#712]
- Because of CI checks, developers no longer have to manually make sure tests / snapshots / linting passes. 
- Docs are ran as apart of CI, so yarn build:full no longer needs to run as apart of the commit process

https://github.com/cbinsights/form-design-system/blob/master/.github/pull_request_template.md

The previous file should remove all steps OTHER than the version bump check

**Comment by SarveshLimaye** [comment]
@reywright can i work on this issue?

**Comment by reywright** [comment]
@SarveshLimaye thanks for your contribution again!
