### ISSUE TITLE
Fix optional flexSettings prop

### ISSUE THREAD

**Issue by David-Cohen35** [cbinsights/form-design-system#962]
flexSettings was initially optional but was not made so during the typeScript conversion and was now causing an error in stories

**Comment by reywright** [comment]
@David-Cohen35 What's the error that happened that prompted this issue? Can we put that in the issue description here?

**Comment by David-Cohen35** [comment]
> @David-Cohen35 What's the error that happened that prompted this issue? Can we put that in the issue description here?

It was originally optional but was being required, causing an error in stories
